### ISSUE TITLE
项目讨论

### ISSUE THREAD

**Issue by gogu** [cat-stride/cat-stride.github.io#2]
此处继续讨论项目方向

**Comment by gogu** [comment]
目前我的想法，除了 Bullet Journal web 版 + 微信助手，还有

- 收集社交网络个人 Timeline 整合成一个的服务，以前用过，现在没得用
- 基于上一个想法，在任意社交网络使用 `#bojo` 标签来记笔记，收集所有零散笔记整合成一本的服务
- 配色工具集 + 社区

**Comment by sardine2** [comment]
配色工具集+社区这个具体是指什么？
我觉得先完成我们最初构思就不错了。借用BJ@概念拓展到微信。

**Comment by shippomiru** [comment]
gogu指的应该是其它的项目思路吧，不是说要把这些都整合到笔记应用里（感觉

**Comment by gogu** [comment]
嗯，是其他的思路。既然决定了这个就关闭吧。
